import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "./components/rootNav";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
const navlink = [
  {
    id: 1,
    name: "Blog",
    href: "/blog",
  },
  {
    id: 2,
    name: "Deshboard",
    href: "/deshboard",
  },
  {
    id: 3,
    name: "User Inter",
    href: "/userinter",
  },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation navlink={navlink}></Navigation>
        {children}
      </body>
    </html>
  );
}
